---
title: "Predator Summary Tables"
output: html_document
author: Catalina Burch
date (last edited): Aug 4, 2022
---

#This Code replicates the work of Yang et al 2006 to check that our methods are correct

```{r, include=FALSE}
#load libraries
library(readr) 
library(tidyverse)
library(here)
library(taxize)

#load data
raw_stomach_contents <- read_csv(here("data/GOA_Raw_StomachContents.csv"))

```


```{r, include=F}
#warning this chunk will take time to run. 
#creating object with scientific names for Predators
pred_names <- raw_stomach_contents %>% 
  distinct(Pred_name)

pred_list<-(sci2comm(pred_names$Pred_name, simplify = T, db = "ncbi"))
pred_names_df <- rownames_to_column(as.data.frame(do.call(rbind, pred_list)))
colnames(pred_names_df) <- c("Pred_name", "Com_name")

#merging common names with overall dataframe
stomach_contents <- full_join(raw_stomach_contents, pred_names_df, by = "Pred_name")

```

Recreating Table 1

```{r Table 1, echo=FALSE}
#Filter for year 
sc_1999 <- stomach_contents %>% 
  filter(Year == 1999)

#Calculating Summary Sample Sizes
#Full stomachs
F_1999 <- sc_1999 %>% 
  distinct(Hauljoin, Pred_nodc, Pred_specn, Pred_stomwt, Pred_name, Com_name) %>% 
  filter(Pred_stomwt>0) %>% 
  group_by(Pred_name, Com_name) %>% 
  summarise(F = n())

#Empty stomachs
E_1999 <- sc_1999 %>% 
  distinct(Hauljoin, Pred_nodc, Pred_specn, Pred_stomwt, Pred_name) %>% 
  filter(Pred_stomwt == 0) %>% 
  group_by(Pred_name) %>% 
  summarise(E = n())

#Combining F + E into one table
FE_1999 <- full_join(F_1999, E_1999, by = "Pred_name")

#Adding total number of stomachs
FE_1999 <- FE_1999 %>% 
  mutate_all(~replace(., is.na(.), 0)) %>% 
  mutate(T = (E + F), "% Empty" = (E)/(E+F)*100)

#Adding (max, min, and mean) fork lengths, standard deviation and year
T_1999 <- sc_1999 %>% 
  distinct(Hauljoin, Pred_nodc, Pred_specn, Pred_stomwt, Pred_name, Pred_len) %>% 
  filter(Pred_stomwt > 0) %>% 
  group_by(Pred_name) %>% 
  summarise("min" = min(Pred_len), "max" = max(Pred_len),
            "Mean" = mean(Pred_len),
            "+/-SD" = (sd(Pred_len))/2) %>%
  mutate(year = 1999)

#Combining into one table
FET_1999 <- full_join(FE_1999, T_1999, by = "Pred_name")

#saving as cvs
write.csv(FET_1999, file = here("output/table1_1999.csv"))

```


#Recreating Table 2
```{r Table2}

#Filter for year 
sc_2001 <- stomach_contents %>% 
  filter(Year == 2001)

#Calculating Summary Sample Sizes
#Full stomachs
F_2001 <- sc_2001 %>% 
  distinct(Hauljoin, Pred_nodc, Pred_specn, Pred_stomwt, Pred_name, Com_name) %>%
  filter(Pred_stomwt>0) %>% 
  group_by(Pred_name, Com_name) %>% 
  summarise(F = n())

#Empty stomachs
E_2001 <- sc_2001 %>% 
  distinct(Hauljoin, Pred_nodc, Pred_specn, Pred_stomwt, Pred_name) %>%
  filter(Pred_stomwt == 0) %>%
  group_by(Pred_name) %>% 
  summarise(E = n())

#Combining F + E into one table
FE_2001 <- full_join(F_2001, E_2001, by = "Pred_name")

#Adding total number of stomachs
FE_2001 <- FE_2001 %>% 
  mutate_all(~replace(., is.na(.), 0)) %>% 
  mutate(T = (E + F), "% Empty" = (E)/(E+F)*100)

#Adding (max, min, and mean) length and standard deviation and year
T_2001 <- sc_2001 %>% 
  distinct(Hauljoin, Pred_nodc, Pred_specn, Pred_stomwt, Pred_name, Pred_len) %>% 
  filter(Pred_stomwt > 0) %>% 
  group_by(Pred_name) %>% 
  summarise("min" = min(Pred_len),"max" = max(Pred_len),
            "Mean" = mean(Pred_len),
            "+/-SD" = (sd(Pred_len))/2) %>%
  mutate(year = 2001)

#Combining into one table
FET_2001 <- full_join(FE_2001, T_2001, by = "Pred_name")

#saving as cvs
write.csv(FET_2001, file = here("output/table2_2001.csv"))

```



Creating tables for the other years and then joining into one big spreadsheet
```{r summary tables}
#These are the years not included in Yang et al: 2003 2005 2007 2009 2011 2013 2015 2017 2019 

############YEAR 2003
#Filter for year 
sc_2003 <- stomach_contents %>% 
  filter(Year == 2003)

#Calculating Summary Sample Sizes
#Full stomachs
F_2003 <- sc_2003 %>% 
  distinct(Hauljoin, Pred_nodc, Pred_specn, Pred_stomwt, Pred_name, Com_name) %>%
  filter(Pred_stomwt>0) %>% 
  group_by(Pred_name, Com_name) %>% 
  summarise(F = n())

#Empty stomachs
E_2003 <- sc_2003 %>% 
  distinct(Hauljoin, Pred_nodc, Pred_specn, Pred_stomwt, Pred_name) %>%
  filter(Pred_stomwt == 0) %>% 
  group_by(Pred_name) %>% 
  summarise(E = n())

#Combining F + E into one table
FE_2003 <- full_join(F_2003, E_2003, by = "Pred_name")

#Adding total number of stomachs
FE_2003 <- FE_2003 %>% 
  mutate_all(~replace(., is.na(.), 0)) %>%
  mutate(T = (E + F), "% Empty" = (E)/(E+F)*100)

#Adding (max, min, and mean) length and standard deviation and year
T_2003 <- sc_2003 %>% 
  distinct(Hauljoin, Pred_nodc, Pred_specn, Pred_stomwt, Pred_name, Pred_len) %>% 
  filter(Pred_stomwt > 0) %>% 
  group_by(Pred_name) %>% 
  summarise("max" = max(Pred_len), "min" = min(Pred_len),
            "Mean" = mean(Pred_len),
            "+/-SD" = (sd(Pred_len))/2) %>%
  mutate(year = 2003)

#Combining into one table
FET_2003 <- full_join(FE_2003, T_2003, by = "Pred_name")

############YEAR 2005
#Filter for year 
sc_2005 <- stomach_contents %>% 
  filter(Year == 2005)

#Calculating Summary Sample Sizes
#Full stomachs
F_2005 <- sc_2005 %>% 
  distinct(Hauljoin, Pred_nodc, Pred_specn, Pred_stomwt, Pred_name, Com_name) %>% 
  filter(Pred_stomwt>0) %>% 
  group_by(Pred_name, Com_name) %>% 
  summarise(F = n())

#Empty stomachs
E_2005 <- sc_2005 %>%
  distinct(Hauljoin, Pred_nodc, Pred_specn, Pred_stomwt, Pred_name) %>%
  filter(Pred_stomwt == 0) %>% 
  group_by(Pred_name) %>% 
  summarise(E = n())

#Combining F + E into one table
FE_2005 <- full_join(F_2005, E_2005, by = "Pred_name")

#Adding total number of stomachs
FE_2005 <- FE_2005 %>% 
  mutate_all(~replace(., is.na(.), 0)) %>% 
  mutate(T = (E + F), "% Empty" = (E)/(E+F)*100)

#Adding (max, min, and mean) length and standard deviation and year
T_2005 <- sc_2005 %>% 
  distinct(Hauljoin, Pred_nodc, Pred_specn, Pred_stomwt, Pred_name, Pred_len) %>% 
  filter(Pred_stomwt > 0) %>% 
  group_by(Pred_name) %>% 
  summarise("max" = max(Pred_len), "min" = min(Pred_len),
            "Mean" = mean(Pred_len),
            "+/-SD" = (sd(Pred_len))/2) %>%
  mutate(year = 2005)

#Combining into one table
FET_2005 <- full_join(FE_2005, T_2005, by = "Pred_name")

############YEAR 2007
#Filter for year 
sc_2007 <- stomach_contents %>% 
  filter(Year == 2007)

#Calculating Summary Sample Sizes
#Full stomachs
F_2007 <- sc_2007 %>% 
  distinct(Hauljoin, Pred_nodc, Pred_specn, Pred_stomwt, Pred_name, Com_name) %>%
  filter(Pred_stomwt>0) %>% 
  group_by(Pred_name, Com_name) %>% 
  summarise(F = n())

#Empty stomachs
E_2007 <- sc_2007 %>% 
  distinct(Hauljoin, Pred_nodc, Pred_specn, Pred_stomwt, Pred_name) %>% 
  filter(Pred_stomwt == 0) %>% 
  group_by(Pred_name) %>% 
  summarise(E = n())

#Combining F + E into one table
FE_2007 <- full_join(F_2007, E_2007, by = "Pred_name")

#Adding total number of stomachs
FE_2007 <- FE_2007 %>% 
  mutate_all(~replace(., is.na(.), 0)) %>% 
  mutate(T = (E + F), "% Empty" = (E)/(E+F)*100)

#Adding (max, min, and mean) length and standard deviation and year
T_2007 <- sc_2007 %>% 
  distinct(Hauljoin, Pred_nodc, Pred_specn, Pred_stomwt, Pred_name, Pred_len) %>% 
  filter(Pred_stomwt > 0) %>% 
  group_by(Pred_name) %>% 
  summarise("max" = max(Pred_len), "min" = min(Pred_len),
            "Mean" = mean(Pred_len),
            "+/-SD" = (sd(Pred_len))/2) %>%
  mutate(year = 2007)


#Combining into one table
FET_2007 <- full_join(FE_2007, T_2007, by = "Pred_name")

############YEAR 2009
#Filter for year 
sc_2009 <- stomach_contents %>% 
  filter(Year == 2009)

#Calculating Summary Sample Sizes
#Full stomachs
F_2009 <- sc_2009 %>% 
  distinct(Hauljoin, Pred_nodc, Pred_specn, Pred_stomwt, Pred_name, Com_name) %>%
  filter(Pred_stomwt>0) %>% 
  group_by(Pred_name, Com_name) %>% 
  summarise(F = n())

#Empty stomachs
E_2009 <- sc_2009 %>% 
  distinct(Hauljoin, Pred_nodc, Pred_specn, Pred_stomwt, Pred_name) %>% 
  filter(Pred_stomwt == 0) %>% 
  group_by(Pred_name) %>% 
  summarise(E = n())

#Combining F + E into one table
FE_2009 <- full_join(F_2009, E_2009, by = "Pred_name")

#Adding total number of stomachs
FE_2009 <- FE_2009 %>% 
  mutate_all(~replace(., is.na(.), 0)) %>% 
  mutate(T = (E + F), "% Empty" = (E)/(E+F)*100)

#Adding (max, min, and mean) length and standard deviation and year
T_2009 <- sc_2009 %>% 
  distinct(Hauljoin, Pred_nodc, Pred_specn, Pred_stomwt, Pred_name, Pred_len) %>% 
  filter(Pred_stomwt > 0) %>% 
  group_by(Pred_name) %>% 
  summarise("max" = max(Pred_len), "min" = min(Pred_len),
            "Mean" = mean(Pred_len),
            "+/-SD" = (sd(Pred_len))/2) %>%
  mutate(year = 2009)

#Combining into one table
FET_2009 <- full_join(FE_2009, T_2009, by = "Pred_name")

############YEAR 2011
#Filter for year 
sc_2011 <- stomach_contents %>% 
  filter(Year == 2011)

#Calculating Summary Sample Sizes
#Full stomachs
F_2011 <- sc_2011 %>% 
  distinct(Hauljoin, Pred_nodc, Pred_specn, Pred_stomwt, Pred_name, Com_name) %>%
  filter(Pred_stomwt>0) %>% 
  group_by(Pred_name, Com_name) %>% 
  summarise(F = n())

#Empty stomachs
E_2011 <- sc_2011 %>% 
  distinct(Hauljoin, Pred_nodc, Pred_specn, Pred_stomwt, Pred_name) %>% 
  filter(Pred_stomwt == 0) %>% 
  group_by(Pred_name) %>% 
  summarise(E = n())

#Combining F + E into one table
FE_2011 <- full_join(F_2011, E_2011, by = "Pred_name")

#Adding total number of stomachs
FE_2011 <- FE_2011 %>% 
  mutate_all(~replace(., is.na(.), 0)) %>% 
  mutate(T = (E + F), "% Empty" = (E)/(E+F)*100)

#Adding (max, min, and mean) length and standard deviation and year
T_2011 <- sc_2011 %>% 
  distinct(Hauljoin, Pred_nodc, Pred_specn, Pred_stomwt, Pred_name, Pred_len) %>% 
  filter(Pred_stomwt > 0) %>% 
  group_by(Pred_name) %>% 
  summarise("max" = max(Pred_len), "min" = min(Pred_len),
            "Mean" = mean(Pred_len),
            "+/-SD" = (sd(Pred_len))/2) %>%
  mutate(year = 2011)

#Combining into one table
FET_2011 <- full_join(FE_2011, T_2011, by = "Pred_name")

############YEAR 2013
#Filter for year 
sc_2013 <- stomach_contents %>% 
  filter(Year == 2013)

#Calculating Summary Sample Sizes
#Full stomachs
F_2013 <- sc_2013 %>% 
  distinct(Hauljoin, Pred_nodc, Pred_specn, Pred_stomwt, Pred_name, Com_name) %>%
  filter(Pred_stomwt>0) %>% 
  group_by(Pred_name, Com_name) %>% 
  summarise(F = n())

#Empty stomachs
E_2013 <- sc_2013 %>% 
  distinct(Hauljoin, Pred_nodc, Pred_specn, Pred_stomwt, Pred_name) %>% 
  filter(Pred_stomwt == 0) %>% 
  group_by(Pred_name) %>% 
  summarise(E = n())

#Combining F + E into one table
FE_2013 <- full_join(F_2013, E_2013, by = "Pred_name")

#Adding total number of stomachs
FE_2013 <- FE_2013 %>% 
  mutate_all(~replace(., is.na(.), 0)) %>% 
  mutate(T = (E + F), "% Empty" = (E)/(E+F)*100)

#Adding (max, min, and mean) length and standard deviation and year
T_2013 <- sc_2013 %>% 
  distinct(Hauljoin, Pred_nodc, Pred_specn, Pred_stomwt, Pred_name, Pred_len) %>% 
  filter(Pred_stomwt > 0) %>% 
  group_by(Pred_name) %>% 
  summarise("max" = max(Pred_len), "min" = min(Pred_len),
            "Mean" = mean(Pred_len),
            "+/-SD" = (sd(Pred_len))/2) %>%
  mutate(year = 2013)

#Combining into one table
FET_2013 <- full_join(FE_2013, T_2013, by = "Pred_name")

############YEAR 2015
#Filter for year 
sc_2015 <- stomach_contents %>% 
  filter(Year == 2015)

#Calculating Summary Sample Sizes
#Full stomachs
F_2015 <- sc_2015 %>% 
  distinct(Hauljoin, Pred_nodc, Pred_specn, Pred_stomwt, Pred_name, Com_name) %>%
  filter(Pred_stomwt>0) %>% 
  group_by(Pred_name, Com_name) %>% 
  summarise(F = n())

#Empty stomachs
E_2015 <- sc_2015 %>% 
  distinct(Hauljoin, Pred_nodc, Pred_specn, Pred_stomwt, Pred_name) %>% 
  filter(Pred_stomwt == 0) %>% 
  group_by(Pred_name) %>% 
  summarise(E = n())

#Combining F + E into one table
FE_2015 <- full_join(F_2015, E_2015, by = "Pred_name")

#Adding total number of stomachs
FE_2015 <- FE_2015 %>% 
  mutate_all(~replace(., is.na(.), 0)) %>% 
  mutate(T = (E + F), "% Empty" = (E)/(E+F)*100)

#Adding (max, min, and mean) length and standard deviation and year
T_2015 <- sc_2015 %>% 
  distinct(Hauljoin, Pred_nodc, Pred_specn, Pred_stomwt, Pred_name, Pred_len) %>% 
  filter(Pred_stomwt > 0) %>% 
  group_by(Pred_name) %>% 
  summarise("max" = max(Pred_len), "min" = min(Pred_len),
            "Mean" = mean(Pred_len),
            "+/-SD" = (sd(Pred_len))/2) %>%
  mutate(year = 2015)

#Combining into one table
FET_2015 <- full_join(FE_2015, T_2015, by = "Pred_name")

############YEAR 2017
#Filter for year 
sc_2017 <- stomach_contents %>% 
  filter(Year == 2017)

#Calculating Summary Sample Sizes
#Full stomachs
F_2017 <- sc_2017 %>% 
  distinct(Hauljoin, Pred_nodc, Pred_specn, Pred_stomwt, Pred_name, Com_name) %>%
  filter(Pred_stomwt>0) %>% 
  group_by(Pred_name, Com_name) %>% 
  summarise(F = n())

#Empty stomachs
E_2017 <- sc_2017 %>% 
  distinct(Hauljoin, Pred_nodc, Pred_specn, Pred_stomwt, Pred_name) %>% 
  filter(Pred_stomwt == 0) %>% 
  group_by(Pred_name) %>% 
  summarise(E = n())

#Combining F + E into one table
FE_2017 <- full_join(F_2017, E_2017, by = "Pred_name")

#Adding total number of stomachs
FE_2017 <- FE_2017 %>% 
  mutate_all(~replace(., is.na(.), 0)) %>% 
  mutate(T = (E + F), "% Empty" = (E)/(E+F)*100)

#Adding (max, min, and mean) length and standard deviation and year
T_2017 <- sc_2017 %>% 
  distinct(Hauljoin, Pred_nodc, Pred_specn, Pred_stomwt, Pred_name, Pred_len) %>% 
  filter(Pred_stomwt > 0) %>% 
  group_by(Pred_name) %>% 
  summarise("max" = max(Pred_len), "min" = min(Pred_len),
            "Mean" = mean(Pred_len),
            "+/-SD" = (sd(Pred_len))/2) %>%
  mutate(year = 2017)

#Combining into one table
FET_2017 <- full_join(FE_2017, T_2017, by = "Pred_name")

############YEAR 2019
#Filter for year 
sc_2019 <- stomach_contents %>% 
  filter(Year == 2019)

#Calculating Summary Sample Sizes
#Full stomachs
F_2019 <- sc_2019 %>% 
  distinct(Hauljoin, Pred_nodc, Pred_specn, Pred_stomwt, Pred_name, Com_name) %>%
  filter(Pred_stomwt>0) %>% 
  group_by(Pred_name, Com_name) %>% 
  summarise(F = n())

#Empty stomachs
E_2019 <- sc_2019 %>% 
  distinct(Hauljoin, Pred_nodc, Pred_specn, Pred_stomwt, Pred_name) %>% 
  filter(Pred_stomwt == 0) %>% 
  group_by(Pred_name) %>% 
  summarise(E = n())

#Combining F + E into one table
FE_2019 <- full_join(F_2019, E_2019, by = "Pred_name")

#Adding total number of stomachs
FE_2019 <- FE_2019 %>% 
  mutate_all(~replace(., is.na(.), 0)) %>% 
  mutate(T = (E + F), "% Empty" = (E)/(E+F)*100)

#Adding (max, min, and mean) length and standard deviation and year
T_2019 <- sc_2019 %>% 
  distinct(Hauljoin, Pred_nodc, Pred_specn, Pred_stomwt, Pred_name, Pred_len) %>% 
  filter(Pred_stomwt > 0) %>% 
  group_by(Pred_name) %>% 
  summarise("max" = max(Pred_len), "min" = min(Pred_len),
            "Mean" = mean(Pred_len),
            "+/-SD" = (sd(Pred_len))/2) %>%
  mutate(year = 2019)

#Combining into one table
FET_2019 <- full_join(FE_2019, T_2019, by = "Pred_name")
```

#Joining the tables together into one spreadsheet
```{r joining}
joined_summary <- rbind(FET_1999, FET_2001, FET_2003, FET_2005, FET_2007, FET_2009, FET_2011, FET_2013, FET_2015, FET_2017, FET_2019)

#export csv
write.csv(joined_summary, file = here("output/PredSampledSummaryInfo.csv"))

```







